# Makefile for compiling the LaTeX report (report.tex)

# --- Variables ---

# Compiler command
LATEX_COMPILER = xelatex

# Source file
SOURCE = report.tex

# Target PDF file (derived from source name)
TARGET = $(patsubst %.tex,%.pdf,$(SOURCE))

# Auxiliary files generated by LaTeX that we might want to clean up
AUX_FILES = *.aux *.log *.out *.toc *.lof *.lot *.synctex.gz *.fdb_latexmk *.fls *.bbl *.blg *.idx *.ilg *.ind *.lof *.lot *.bcf *.run.xml *.xdv

# --- Targets ---

# Default target: Running 'make' or 'make all' will execute this
# It depends on the final PDF file being created.
all: $(TARGET)

# Rule to create the PDF file from the TeX source file
# It depends on the source file. If report.tex changes, this rule will run.
$(TARGET): $(SOURCE)
	@echo "Compiling $(SOURCE) with $(LATEX_COMPILER)... (First Pass)"
	$(LATEX_COMPILER) $(SOURCE) > /dev/null # Run XeLaTeX, suppress verbose output
	@echo "Compiling $(SOURCE) with $(LATEX_COMPILER)... (Second Pass for references/TOC)"
	$(LATEX_COMPILER) $(SOURCE) > /dev/null # Run again to resolve cross-references, TOC etc.
	@echo "Successfully created $(TARGET)"

# Target to clean up generated files
clean:
	@echo "Cleaning up generated files..."
	rm -f $(TARGET) $(AUX_FILES)
	@echo "Cleanup complete."

# Declare targets that are not actual files
.PHONY: all clean